#!/bin/sh

KEYSTORE=bidkeystore.jks
help() {
	echo "ksimport - import a certificate into a keystore"
	echo "Usage:"
	echo "   ksimport alias certificate [keystore]"
}
keytoolexe=$(which keytool)
if [ ! -x "$keytoolexe" ] ; then
   echo "KeyTool not found. Please ensure your JAVA_HOME is in PATH"
fi
if [ -z "$1" ]; then
	help
	exit 1
fi
if [ -z "$2" ]; then
	help
	exit 1
fi
if [ -n "$3" ]; then
	KEYSTORE=$3
fi
keytool -import -alias $1 -keystore $3 -file $3 


